### ISSUE TITLE
trezor/trezor-address-validator legacy address formats should be forbidden

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-address-validator#3]
i'm not able to add an issue in https://github.com/trezor/trezor-address-validator so i'm putting it here.

Legacy addresses formats for BCH and LTC should be forbidden. We should enforce user to use the proper format instead

https://github.com/trezor/trezor-address-validator/blob/master/test/wallet_address_validator.js#L68
https://github.com/trezor/trezor-address-validator/blob/master/test/wallet_address_validator.js#L95

**Comment by prusnak** [comment]
I enabled issues on this (`trezor-address-validator`) repo and transferred the issue here.

**Comment by martinboehm** [comment]
trezor-address-validator@0.3.20 with requested fixed released.

**Comment by szymonlesisz** [comment]
accept bitcoincash addresses with or without `bitcoincash:` prefix

`bitcoincash:qq4v32mtagxac29my6gwj6fd4tmqg8rysu23dax807`
`qq4v32mtagxac29my6gwj6fd4tmqg8rysu23dax807`

**Comment by martinboehm** [comment]
This 50d7b49e9f11c4aa64d32dacd93d66f46d125fe5 commit fixes the issue with `bitcoincash` prefix.

**Comment by prusnak** [comment]
Thanks, Martin. I see 0.3.21 release on the NPM, so I guess this issue can be closed.
